# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

encrypt <- function(plaintext) {
    .Call(`_DPAPIinterface_encrypt`, plaintext)
}

decrypt <- function(encrypt_vector) {
    .Call(`_DPAPIinterface_decrypt`, encrypt_vector)
}

